apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: minio
    app_name: minio
    application: minio
  name: minio
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app_name: minio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
