#!/bin/bash

usage(){
  echo "========================================"
  echo "USAGE: $0 COMMAND [args]"
  echo "  Command list:"
  echo "    - info        : execute info scripts"
  echo "    - shell       : execute shell scripts"
  echo "    - start       : execute start scripts"
  echo "    - status      : execute status scripts"
  echo "    - test        : execute test scripts"
  echo "========================================"
}

usage
